notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

services:
  - docker

install:
 - docker build -t dockstore-biobambam2 .

script:
 - docker images | grep -c dockstore-biobambam2
